add 04-lection2_01-histogram_v2
js-tasks-ru/htmlcss-20230227_tibr7 pull request #14
Opened 2023-03-15 14:05 UTC by pavelvz

Задача histogram

2023-03-15 14:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-16 11:14 UTC, GSemikozov requested changes

2023-03-16 11:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 26px;
`16px 24px 24px`

2023-03-16 11:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
ширину и высоту удаляем

2023-03-16 11:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__view > a{
просто .histogram__link сразу на `<a>`

2023-03-16 11:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__total_orders{
это элемент а не модификатор = .histogram__total

2023-03-16 11:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height:70px;
50

2023-03-16 11:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__chart_m{
через модификатор не надо, сразу на .histogram__chart

2023-03-16 11:14 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <div class="histogram__view"><a href="/">View all</a></div>
`<a>`

2023-03-16 13:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-16 14:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 21:52 UTC, GSemikozov approved these changes

2023-03-16 21:52 UTC, merged